//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `Landing`.
    static let landing: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "Landing")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 12 storyboards.
  struct storyboard {
    /// Storyboard `FormationListViewController`.
    static let formationListViewController = _R.storyboard.formationListViewController()
    /// Storyboard `FormationTemplateEditViewController`.
    static let formationTemplateEditViewController = _R.storyboard.formationTemplateEditViewController()
    /// Storyboard `FormationTemplateListViewController`.
    static let formationTemplateListViewController = _R.storyboard.formationTemplateListViewController()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `PlayerEditViewController`.
    static let playerEditViewController = _R.storyboard.playerEditViewController()
    /// Storyboard `PlayerListViewController`.
    static let playerListViewController = _R.storyboard.playerListViewController()
    /// Storyboard `TeamEditViewController`.
    static let teamEditViewController = _R.storyboard.teamEditViewController()
    /// Storyboard `TeamListViewController`.
    static let teamListViewController = _R.storyboard.teamListViewController()
    /// Storyboard `TeamMenuViewController`.
    static let teamMenuViewController = _R.storyboard.teamMenuViewController()
    /// Storyboard `TestViewController`.
    static let testViewController = _R.storyboard.testViewController()
    /// Storyboard `TextPicker`.
    static let textPicker = _R.storyboard.textPicker()
    
    /// `UIStoryboard(name: "FormationListViewController", bundle: ...)`
    static func formationListViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.formationListViewController)
    }
    
    /// `UIStoryboard(name: "FormationTemplateEditViewController", bundle: ...)`
    static func formationTemplateEditViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.formationTemplateEditViewController)
    }
    
    /// `UIStoryboard(name: "FormationTemplateListViewController", bundle: ...)`
    static func formationTemplateListViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.formationTemplateListViewController)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "PlayerEditViewController", bundle: ...)`
    static func playerEditViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.playerEditViewController)
    }
    
    /// `UIStoryboard(name: "PlayerListViewController", bundle: ...)`
    static func playerListViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.playerListViewController)
    }
    
    /// `UIStoryboard(name: "TeamEditViewController", bundle: ...)`
    static func teamEditViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.teamEditViewController)
    }
    
    /// `UIStoryboard(name: "TeamListViewController", bundle: ...)`
    static func teamListViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.teamListViewController)
    }
    
    /// `UIStoryboard(name: "TeamMenuViewController", bundle: ...)`
    static func teamMenuViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.teamMenuViewController)
    }
    
    /// `UIStoryboard(name: "TestViewController", bundle: ...)`
    static func testViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.testViewController)
    }
    
    /// `UIStoryboard(name: "TextPicker", bundle: ...)`
    static func textPicker(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.textPicker)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct formationListViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = TeamListViewController
      
      let bundle = R.hostingBundle
      let name = "FormationListViewController"
      
      fileprivate init() {}
    }
    
    struct formationTemplateEditViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = FormationTemplateEditViewController
      
      let bundle = R.hostingBundle
      let name = "FormationTemplateEditViewController"
      
      fileprivate init() {}
    }
    
    struct formationTemplateListViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = FormationTemplateListViewController
      
      let bundle = R.hostingBundle
      let name = "FormationTemplateListViewController"
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    struct playerEditViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = PlayerEditViewController
      
      let bundle = R.hostingBundle
      let name = "PlayerEditViewController"
      
      fileprivate init() {}
    }
    
    struct playerListViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = PlayerListViewController
      
      let bundle = R.hostingBundle
      let name = "PlayerListViewController"
      
      fileprivate init() {}
    }
    
    struct teamEditViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = TeamEditViewController
      
      let bundle = R.hostingBundle
      let name = "TeamEditViewController"
      
      fileprivate init() {}
    }
    
    struct teamListViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = TeamListViewController
      
      let bundle = R.hostingBundle
      let name = "TeamListViewController"
      
      fileprivate init() {}
    }
    
    struct teamMenuViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = TeamMenuViewController
      
      let bundle = R.hostingBundle
      let name = "TeamMenuViewController"
      
      fileprivate init() {}
    }
    
    struct testViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = TestViewController
      
      let bundle = R.hostingBundle
      let name = "TestViewController"
      
      fileprivate init() {}
    }
    
    struct textPicker: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = TextPicker
      
      let bundle = R.hostingBundle
      let name = "TextPicker"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
